const predefinedTexts = [

  {
    label: "Anniversaire Festif",
    text: "Joyeux Anniversaire !",
    fontFamily: "Comic Sans MS",
    fontSize: 42,
    fill: "#FF4081",
    align: "center",
    fontStyle: "italic",
    textDecoration: "",
    letterSpacing: 1,
    lineHeight: 1.2
  },
  {
    label: "Mariage Élégant",
    text: "Félicitations aux mariés",
    fontFamily: "Great Vibes",
    fontSize: 38,
    fill: "#B388FF",
    align: "center",
    fontStyle: "italic",
    textDecoration: "",
    letterSpacing: 1,
    lineHeight: 1.2
  },
  {
    label: "Invitation Chic",
    text: "Vous êtes invités",
    fontFamily: "Georgia",
    fontSize: 36,
    fill: "#444444",
    align: "center",
    fontStyle: "italic",
    textDecoration: "underline",
    letterSpacing: 1,
    lineHeight: 1.2
  },
  {
    label: "Nouvel An",
    text: "Bonne Année !",
    fontFamily: "Arial Black",
    fontSize: 40,
    fill: "#FFD700",
    align: "center",
    fontStyle: "bold",
    textDecoration: "",
    letterSpacing: 2,
    lineHeight: 1.1
  },
  {
    label: "Naissance Douce",
    text: "Bienvenue au bébé",
    fontFamily: "Dancing Script",
    fontSize: 34,
    fill: "#FFB6C1",
    align: "center",
    fontStyle: "italic",
    textDecoration: "",
    letterSpacing: 0,
    lineHeight: 1.1
  },
  {
    label: "Fête Surprise",
    text: "Surprise !",
    fontFamily: "Pacifico",
    fontSize: 38,
    fill: "#FF5722",
    align: "center",
    fontStyle: "normal",
    textDecoration: "",
    letterSpacing: 1,
    lineHeight: 1.1
  },
  {
    label: "Promo Flash",
    text: "Vente Éclair",
    fontFamily: "Impact",
    fontSize: 40,
    fill: "#D50000",
    align: "center",
    fontStyle: "bold",
    textDecoration: "underline",
    letterSpacing: 2,
    lineHeight: 1.1
  },
  {
    label: "Motivation",
    text: "Tu peux le faire !",
    fontFamily: "Caveat",
    fontSize: 36,
    fill: "#009688",
    align: "center",
    fontStyle: "italic",
    textDecoration: "",
    letterSpacing: 0,
    lineHeight: 1.3
  },
  {
    label: "Halloween",
    text: "Joyeux Halloween",
    fontFamily: "Creepster",
    fontSize: 38,
    fill: "#8E24AA",
    align: "center",
    fontStyle: "normal",
    textDecoration: "",
    letterSpacing: 1,
    lineHeight: 1.1
  },
  {
    label: "Fête des Mères",
    text: "Bonne fête Maman",
    fontFamily: "Great Vibes",
    fontSize: 34,
    fill: "#E91E63",
    align: "center",
    fontStyle: "italic",
    textDecoration: "",
    letterSpacing: 0,
    lineHeight: 1.2
  },
  {
    label: "Fête des Pères",
    text: "Bonne fête Papa",
    fontFamily: "Rockwell",
    fontSize: 34,
    fill: "#3E2723",
    align: "center",
    fontStyle: "bold",
    textDecoration: "",
    letterSpacing: 1,
    lineHeight: 1.2
  },
  {
    label: "Summer Vibes",
    text: "Hello Summer",
    fontFamily: "Fredoka One",
    fontSize: 36,
    fill: "#FFA726",
    align: "center",
    fontStyle: "normal",
    textDecoration: "",
    letterSpacing: 1,
    lineHeight: 1.1
  },
  {
    label: "Bonne Chance",
    text: "Good Luck!",
    fontFamily: "Courier New",
    fontSize: 32,
    fill: "#4CAF50",
    align: "center",
    fontStyle: "italic",
    textDecoration: "",
    letterSpacing: 0,
    lineHeight: 1.1
  },
  {
    label: "Rentrée Scolaire",
    text: "Bonne rentrée",
    fontFamily: "Arial",
    fontSize: 34,
    fill: "#3F51B5",
    align: "center",
    fontStyle: "bold",
    textDecoration: "",
    letterSpacing: 1,
    lineHeight: 1.1
  },
  {
    label: "Hiver Magique",
    text: "Winter Wonderland",
    fontFamily: "Snell Roundhand",
    fontSize: 36,
    fill: "#90CAF9",
    align: "center",
    fontStyle: "italic",
    textDecoration: "",
    letterSpacing: 0,
    lineHeight: 1.2
  },
  {
    label: "Vacances",
    text: "Bonnes Vacances !",
    fontFamily: "Verdana",
    fontSize: 32,
    fill: "#FF9800",
    align: "center",
    fontStyle: "normal",
    textDecoration: "",
    letterSpacing: 1,
    lineHeight: 1.1
  },
  {
    label: "Remerciement",
    text: "Merci beaucoup",
    fontFamily: "Brush Script MT",
    fontSize: 36,
    fill: "#673AB7",
    align: "center",
    fontStyle: "italic",
    textDecoration: "",
    letterSpacing: 0,
    lineHeight: 1.1
  },
  {
    label: "Retour",
    text: "Nous sommes de retour",
    fontFamily: "Impact",
    fontSize: 34,
    fill: "#388E3C",
    align: "center",
    fontStyle: "bold",
    textDecoration: "",
    letterSpacing: 2,
    lineHeight: 1.1
  },
  {
    label: "Soirée",
    text: "Soirée spéciale",
    fontFamily: "Lobster",
    fontSize: 36,
    fill: "#F06292",
    align: "center",
    fontStyle: "normal",
    textDecoration: "",
    letterSpacing: 1,
    lineHeight: 1.1
  },
  {
    label: "Nouvelle Collection",
    text: "Découvrez notre nouvelle collection",
    fontFamily: "Roboto",
    fontSize: 30,
    fill: "#000000",
    align: "center",
    fontStyle: "normal",
    textDecoration: "",
    letterSpacing: 0,
    lineHeight: 1.2
  }

];

export default predefinedTexts;
